/* Hand-written, standing in for what Stage 7 (harpia's ZmqAdapter) would
 * eventually generate from the human root .harpia file that imports
 * Janus's janus_generated.harpia — see architecture.md's Stage 7 open
 * question, which this demo sidesteps rather than resolves. Human/vendor
 * owned, never regenerated by Janus, same as src/display_driver.c.
 */
#ifndef JANUS_BINDINGS_H
#define JANUS_BINDINGS_H

typedef struct {
    const char *name;
    int battery_level;
    int online;
} device_t;

extern device_t device_instance;

#endif /* JANUS_BINDINGS_H */
