"""Janus's CLI: Stage 1 -> 2 -> 3a -> 3b in one command. Parses an
app.yaml (Stage 0's origin file), runs the layout pass, and writes the
generated harpia Include + embedded-C files to a target directory —
content-diffed, same as `generate.write_project` on its own. See
architecture.md for what each stage produces.

Installed as the `janus-generate` console script (pyproject.toml); also
runnable directly as `python3 -m janus.cli`.
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

from .generate import write_project
from .stage1_parse.dsl_yaml import parse_app
from .stage2_layout.layout import check_fits_display, layout_screen
from .stage3b_embedded_c.emit_files import render_render_config_header
from .stage5_actions.scaffold_actions import scaffold_actions_c
from .stage8_scaffold.scaffold_main import scaffold_main_c
from .writer import copy_tree_if_changed, write_if_changed

# runtime/embedded_c/ lives two levels up from this file (janus/cli.py ->
# repo root). Only the fixed library itself is vendored — CMakeLists.txt,
# include/, src/, tests/, host_mock/ — never build/ (a CMake artifact
# directory, regenerated by the consuming project's own build, not ours).
_RUNTIME_EMBEDDED_C = Path(__file__).resolve().parents[1] / "runtime" / "embedded_c"
_VENDORED_SUBDIRS = ("include", "src", "tests", "host_mock")


def _vendor_runtime(dest_dir: Path, render_mode: str) -> list[Path]:
    written = []
    cmakelists = _RUNTIME_EMBEDDED_C / "CMakeLists.txt"
    if write_if_changed(dest_dir / "CMakeLists.txt", cmakelists.read_text()):
        written.append(dest_dir / "CMakeLists.txt")
    for subdir in _VENDORED_SUBDIRS:
        written.extend(copy_tree_if_changed(_RUNTIME_EMBEDDED_C / subdir, dest_dir / subdir))

    # The one generated file that lands *inside* the vendored fixed
    # library: janus_runtime.{c,h} pull it in via __has_include so a
    # `blocking` project compiles out the polled/async render path (and
    # its 6912-byte g_async_ops buffer — channel_icons task 3). Written
    # for `blocking` too, macro undefined, so the include never dangles.
    cfg = dest_dir / "include" / "janus_render_config.gen.h"
    if write_if_changed(cfg, render_render_config_header(render_mode)):
        written.append(cfg)
    return written


def generate(
    app_yaml: str | Path,
    target_dir: str | Path,
    scaffold_src: str | Path | None = None,
) -> list[Path]:
    """Runs the pipeline against `app_yaml` and writes everything Stage
    3a/3b produce into `target_dir` (`.c` under `target_dir/src`, `.h`
    under `target_dir/include` — see `write_project`). If `scaffold_src`
    is given, this is scaffold mode: `main.c`/`janus_actions.c` get
    scaffolded there the first time they're needed (Stage 5/8, never
    touched again once they exist), and the fixed `runtime/embedded_c`
    library is vendored into `target_dir/runtime` (content-diffed, same
    discipline as every other Janus output) so the project can build
    against its own copy instead of reaching into the Janus checkout.
    Without `scaffold_src`, neither happens — `target_dir` holds only the
    regenerated-every-run Janus output. Returns every path actually
    written (empty on a no-op re-run)."""
    app = parse_app(app_yaml)
    for screen in app.screens:
        layout_screen(screen, app.display)
        if app.display is not None:
            check_fits_display(screen, app.display)

    target_dir = Path(target_dir)
    written = write_project(app, target_dir)

    if scaffold_src is not None:
        scaffold_src = Path(scaffold_src)
        if scaffold_actions_c(app, scaffold_src / "janus_actions.c"):
            written.append(scaffold_src / "janus_actions.c")
        if scaffold_main_c(app, scaffold_src / "main.c"):
            written.append(scaffold_src / "main.c")
        render_mode = app.display.render_mode if app.display is not None else "blocking"
        written.extend(_vendor_runtime(target_dir / "runtime", render_mode))

    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="janus-generate",
        description="Run Janus against an app.yaml and write the generated output to a target folder.",
    )
    parser.add_argument("app_yaml", type=Path, help="path to the project's app.yaml (the origin file)")
    parser.add_argument("target_dir", type=Path, help="directory to write generated files into")
    parser.add_argument(
        "--scaffold-src",
        type=Path,
        default=None,
        metavar="DIR",
        help=(
            "scaffold mode: also scaffold src/main.c and src/janus_actions.c "
            "under DIR if they don't exist yet, and vendor the fixed "
            "runtime/embedded_c library into target_dir/runtime"
        ),
    )
    args = parser.parse_args(argv)

    # Generation is "log and keep going" for soft failures (an image
    # asset that won't decode, an oversized bitmap) — surface those on
    # stderr instead of letting them pass silently.
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")

    if not args.app_yaml.is_file():
        parser.error(f"{args.app_yaml}: no such file")

    written = generate(args.app_yaml, args.target_dir, args.scaffold_src)
    for path in written:
        print(f"wrote {path}")
    if not written:
        print("nothing changed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
